/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allography extends org.jooq.impl.TableImpl<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> {

	private static final long serialVersionUID = -1713090091;

	/**
	 * The singleton instance of <code>chinese.allography</code>
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Allography ALLOGRAPHY = new com.piotr2b.chinesehuawen.entities.tables.Allography();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> getRecordType() {
		return com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord.class;
	}

	/**
	 * The column <code>chinese.allography.cp</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord, java.lang.String> CP = createField("cp", org.jooq.impl.SQLDataType.VARCHAR.length(12).nullable(false), this, "");

	/**
	 * The column <code>chinese.allography.class</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord, java.lang.Integer> CLASS = createField("class", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>chinese.allography</code> table reference
	 */
	public Allography() {
		this("allography", null);
	}

	/**
	 * Create an aliased <code>chinese.allography</code> table reference
	 */
	public Allography(java.lang.String alias) {
		this(alias, com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY);
	}

	private Allography(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Allography(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.piotr2b.chinesehuawen.entities.Chinese.CHINESE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> getPrimaryKey() {
		return com.piotr2b.chinesehuawen.entities.Keys.KEY_ALLOGRAPHY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord>>asList(com.piotr2b.chinesehuawen.entities.Keys.KEY_ALLOGRAPHY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord, ?>>asList(com.piotr2b.chinesehuawen.entities.Keys.ALLOGRAPHY_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.piotr2b.chinesehuawen.entities.tables.Allography as(java.lang.String alias) {
		return new com.piotr2b.chinesehuawen.entities.tables.Allography(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.piotr2b.chinesehuawen.entities.tables.Allography rename(java.lang.String name) {
		return new com.piotr2b.chinesehuawen.entities.tables.Allography(name, null);
	}
}
