/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sinogram extends org.jooq.impl.TableImpl<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> {

	private static final long serialVersionUID = 1973408152;

	/**
	 * The singleton instance of <code>chinese.sinogram</code>
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Sinogram SINOGRAM = new com.piotr2b.chinesehuawen.entities.tables.Sinogram();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> getRecordType() {
		return com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord.class;
	}

	/**
	 * The column <code>chinese.sinogram.cp</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.String> CP = createField("cp", org.jooq.impl.SQLDataType.VARCHAR.length(12).nullable(false), this, "");

	/**
	 * The column <code>chinese.sinogram.semantics</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.String> SEMANTICS = createField("semantics", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>chinese.sinogram.consonants</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.String> CONSONANTS = createField("consonants", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

	/**
	 * The column <code>chinese.sinogram.rhyme</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.String> RHYME = createField("rhyme", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

	/**
	 * The column <code>chinese.sinogram.tone</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.Integer> TONE = createField("tone", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>chinese.sinogram.stroke</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.Byte> STROKE = createField("stroke", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>chinese.sinogram.frequency</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord, java.lang.Byte> FREQUENCY = createField("frequency", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>chinese.sinogram</code> table reference
	 */
	public Sinogram() {
		this("sinogram", null);
	}

	/**
	 * Create an aliased <code>chinese.sinogram</code> table reference
	 */
	public Sinogram(java.lang.String alias) {
		this(alias, com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM);
	}

	private Sinogram(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sinogram(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.piotr2b.chinesehuawen.entities.Chinese.CHINESE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> getPrimaryKey() {
		return com.piotr2b.chinesehuawen.entities.Keys.KEY_SINOGRAM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord>>asList(com.piotr2b.chinesehuawen.entities.Keys.KEY_SINOGRAM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.piotr2b.chinesehuawen.entities.tables.Sinogram as(java.lang.String alias) {
		return new com.piotr2b.chinesehuawen.entities.tables.Sinogram(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.piotr2b.chinesehuawen.entities.tables.Sinogram rename(java.lang.String name) {
		return new com.piotr2b.chinesehuawen.entities.tables.Sinogram(name, null);
	}
}
