/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Structure extends org.jooq.impl.TableImpl<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> {

	private static final long serialVersionUID = -1438758699;

	/**
	 * The singleton instance of <code>chinese.structure</code>
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Structure STRUCTURE = new com.piotr2b.chinesehuawen.entities.tables.Structure();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> getRecordType() {
		return com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord.class;
	}

	/**
	 * The column <code>chinese.structure.father_cp</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, java.lang.String> FATHER_CP = createField("father_cp", org.jooq.impl.SQLDataType.VARCHAR.length(12).nullable(false), this, "");

	/**
	 * The column <code>chinese.structure.son_cp</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, java.lang.String> SON_CP = createField("son_cp", org.jooq.impl.SQLDataType.VARCHAR.length(12).nullable(false), this, "");

	/**
	 * The column <code>chinese.structure.idc</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, com.piotr2b.chinesehuawen.entities.enums.StructureIdc> IDC = createField("idc", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.piotr2b.chinesehuawen.entities.enums.StructureIdc.class), this, "");

	/**
	 * The column <code>chinese.structure.ordinal</code>.
	 */
	public final org.jooq.TableField<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, java.lang.Integer> ORDINAL = createField("ordinal", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>chinese.structure</code> table reference
	 */
	public Structure() {
		this("structure", null);
	}

	/**
	 * Create an aliased <code>chinese.structure</code> table reference
	 */
	public Structure(java.lang.String alias) {
		this(alias, com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE);
	}

	private Structure(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> aliased) {
		this(alias, aliased, null);
	}

	private Structure(java.lang.String alias, org.jooq.Table<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.piotr2b.chinesehuawen.entities.Chinese.CHINESE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> getPrimaryKey() {
		return com.piotr2b.chinesehuawen.entities.Keys.KEY_STRUCTURE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord>>asList(com.piotr2b.chinesehuawen.entities.Keys.KEY_STRUCTURE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord, ?>>asList(com.piotr2b.chinesehuawen.entities.Keys.STRUCTURE_IBFK_1, com.piotr2b.chinesehuawen.entities.Keys.STRUCTURE_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.piotr2b.chinesehuawen.entities.tables.Structure as(java.lang.String alias) {
		return new com.piotr2b.chinesehuawen.entities.tables.Structure(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.piotr2b.chinesehuawen.entities.tables.Structure rename(java.lang.String name) {
		return new com.piotr2b.chinesehuawen.entities.tables.Structure(name, null);
	}
}
