/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllographyRecord extends org.jooq.impl.UpdatableRecordImpl<com.piotr2b.chinesehuawen.entities.tables.records.AllographyRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 807243820;

	/**
	 * Setter for <code>huawen.allography.cp</code>.
	 */
	public void setCp(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>huawen.allography.cp</code>.
	 */
	public java.lang.String getCp() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>huawen.allography.class</code>.
	 */
	public void setClass_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>huawen.allography.class</code>.
	 */
	public java.lang.Integer getClass_() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY.CP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY.CLASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getClass_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllographyRecord value1(java.lang.String value) {
		setCp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllographyRecord value2(java.lang.Integer value) {
		setClass_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AllographyRecord values(java.lang.String value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AllographyRecord
	 */
	public AllographyRecord() {
		super(com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY);
	}

	/**
	 * Create a detached, initialised AllographyRecord
	 */
	public AllographyRecord(java.lang.String cp, java.lang.Integer class_) {
		super(com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY);

		setValue(0, cp);
		setValue(1, class_);
	}
}
