/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SinogramRecord extends org.jooq.impl.UpdatableRecordImpl<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 436131383;

	/**
	 * Setter for <code>huawen.sinogram.hash</code>.
	 */
	public void setHash(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>huawen.sinogram.hash</code>.
	 */
	public java.lang.String getHash() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>huawen.sinogram.ids</code>.
	 */
	public void setIds(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>huawen.sinogram.ids</code>.
	 */
	public java.lang.String getIds() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM.HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM.IDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getIds();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SinogramRecord value1(java.lang.String value) {
		setHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SinogramRecord value2(java.lang.String value) {
		setIds(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SinogramRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SinogramRecord
	 */
	public SinogramRecord() {
		super(com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM);
	}

	/**
	 * Create a detached, initialised SinogramRecord
	 */
	public SinogramRecord(java.lang.String hash, java.lang.String ids) {
		super(com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM);

		setValue(0, hash);
		setValue(1, ids);
	}
}
