/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StructureRecord extends org.jooq.impl.UpdatableRecordImpl<com.piotr2b.chinesehuawen.entities.tables.records.StructureRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, com.piotr2b.chinesehuawen.entities.enums.StructureIdc, java.lang.Integer> {

	private static final long serialVersionUID = 75049487;

	/**
	 * Setter for <code>huawen.structure.father_cp</code>.
	 */
	public void setFatherCp(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>huawen.structure.father_cp</code>.
	 */
	public java.lang.String getFatherCp() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>huawen.structure.son_cp</code>.
	 */
	public void setSonCp(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>huawen.structure.son_cp</code>.
	 */
	public java.lang.String getSonCp() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>huawen.structure.idc</code>.
	 */
	public void setIdc(com.piotr2b.chinesehuawen.entities.enums.StructureIdc value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>huawen.structure.idc</code>.
	 */
	public com.piotr2b.chinesehuawen.entities.enums.StructureIdc getIdc() {
		return (com.piotr2b.chinesehuawen.entities.enums.StructureIdc) getValue(2);
	}

	/**
	 * Setter for <code>huawen.structure.ordinal</code>.
	 */
	public void setOrdinal(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>huawen.structure.ordinal</code>.
	 */
	public java.lang.Integer getOrdinal() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record4<java.lang.String, java.lang.String, com.piotr2b.chinesehuawen.entities.enums.StructureIdc, java.lang.Integer> key() {
		return (org.jooq.Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, com.piotr2b.chinesehuawen.entities.enums.StructureIdc, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, com.piotr2b.chinesehuawen.entities.enums.StructureIdc, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE.FATHER_CP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE.SON_CP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.piotr2b.chinesehuawen.entities.enums.StructureIdc> field3() {
		return com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE.IDC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE.ORDINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getFatherCp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSonCp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.piotr2b.chinesehuawen.entities.enums.StructureIdc value3() {
		return getIdc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getOrdinal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value1(java.lang.String value) {
		setFatherCp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value2(java.lang.String value) {
		setSonCp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value3(com.piotr2b.chinesehuawen.entities.enums.StructureIdc value) {
		setIdc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value4(java.lang.Integer value) {
		setOrdinal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord values(java.lang.String value1, java.lang.String value2, com.piotr2b.chinesehuawen.entities.enums.StructureIdc value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StructureRecord
	 */
	public StructureRecord() {
		super(com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE);
	}

	/**
	 * Create a detached, initialised StructureRecord
	 */
	public StructureRecord(java.lang.String fatherCp, java.lang.String sonCp, com.piotr2b.chinesehuawen.entities.enums.StructureIdc idc, java.lang.Integer ordinal) {
		super(com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE);

		setValue(0, fatherCp);
		setValue(1, sonCp);
		setValue(2, idc);
		setValue(3, ordinal);
	}
}
