/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>huawen</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> KEY_SINOGRAM_PRIMARY = UniqueKeys0.KEY_SINOGRAM_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.piotr2b.chinesehuawen.entities.tables.records.SinogramRecord> KEY_SINOGRAM_PRIMARY = createUniqueKey(com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM, com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM.HASH);
	}
}
