/**
 * This class is generated by jOOQ
 */
package com.piotr2b.chinesehuawen.entities;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in huawen
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table huawen.allography
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Allography ALLOGRAPHY = com.piotr2b.chinesehuawen.entities.tables.Allography.ALLOGRAPHY;

	/**
	 * The table huawen.sinogram
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Sinogram SINOGRAM = com.piotr2b.chinesehuawen.entities.tables.Sinogram.SINOGRAM;

	/**
	 * The table huawen.structure
	 */
	public static final com.piotr2b.chinesehuawen.entities.tables.Structure STRUCTURE = com.piotr2b.chinesehuawen.entities.tables.Structure.STRUCTURE;
}
